- name: Demo on vars usage  
  hosts: all    
  vars:                                   # Global Variables : All the tasks of this play can access this variable 
    URL: play.google.com    
  vars_files: 
    - "{{ENV}}.yml"
  vars_prompt:
    - name: URNAME
      prompt: Enter your name 
      private: false                
  tasks: 
    - name: Printing the variable 
      ansible.builtin.debug:
        msg: Value of the URL is {{URL}}

    - name: Demo on using local variable
      ansible.builtin.debug:
        msg: Value of the URL's is {{URL}}
      vars: 
        URL: task.google.com
# - name: Demo on using undelated variable 
    #   ansible.builtin.debug:
    #     msg: Value of CLIURL is {{CLIURL}}

    # - name: Printing prompt variable  
    #   ansible.builtin.debug:
    #     msg: Name of the person is {{URNAME}}
    - name: This is env specific
      ansible.builtin.debug:
        msg: Type Of Instance To Be Used {{INS_TYPE}}


# PS : If you try to print a variable that is not declared, it will throw an error.

# Variable Precedence : 

### CLI Variables > Local Variable > Global Variable 
