- name: Demo on vars usage
  hosts: all
  vars:                                  # Global Variables : All the tasks of this play can access this variable                            
   URL: play.google.com      
  tasks:
   - name: printing the variable
     ansible.builtin.debug:
       msg: value of the URL is {{URL}} 

   - name: Demo on Printing the local variable
     ansible.builtin.debug:
       msg: value of the URL is {{URL}} 
     vars:
      URL: task.google.com
