- name: Demo on facts
  hosts: all
  # gather_facts: no     If you don't need facts to be gathered, we can mention this as no.           
  tasks: 
    - name: Printing the default variable 
      ansible.builtin.debug:
        msg: Server Flavor Is {{ansible_distribution}}

    - name: Printing the mac address
      ansible.builtin.debug:
        msg: Mac Address Of The Node Is {{ansible_default_ipv4.macaddress}}