- name: Demo on using tags
  hosts: all
  tasks: 
    - name: This is a frontend task 
      ansible.builtin.debug:
        msg: Installing frontend
    - name: starting frontend 
      ansible.builtin.debug:
        msg: starting frontend

    - name: This is a backend task 
      ansible.builtin.debug:
        msg: Installing backend
    - name: starting backend 
      ansible.builtin.debug:
        msg: starting  backend

    - name: This is a DB task 
      ansible.builtin.debug:
        msg: Installing DB 
    - name: starting a DB task
      ansible.builtin.debug:
        msg: starting DB 
    


    

      
