- name: Demo on package installation  
  hosts: all 
  become: yes
  tasks: 
    - name: Removing Nginx
      ansible.builtin.package:
        name: nginx 
        state: absent 

    - name: Installing httpd
      ansible.builtin.package:
        name:
          - httpd 
          - jq 
        state: present
