- name: configuring the nodejs
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | bash - 

- name: Installing Nodejs
  ansible.builtin.package:
    name: nodejs 
    state: present

- name: creating {{APPUSER}}
  ansible.builtin.user:
    name: {{APPUSER}}
    comment: roboshop app users

- name: Download and extracting {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
    dest: /tmp 
    remote_src: yes

- name: Performing {{COMPONENT}} Cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent
  ignore_errors: yes



