- name: Copying the systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Starting {{COMPONENT}} 
  systemd:
    name: "{{COMPONENT}}"
    state: started
    enabled: yes
    daemon_reload: yes     

- name: configuring the service name
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}