- name: Installing maven on {{COMPONENT}}-{{ENV}} server
  ansible.builtin.package:
    name: maven 
    state: present

- name: Creating App User
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: download and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract

- name: Generating the artifacts with npm install
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/
    
- name: Configuring {{COMPONENT}} the service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: configuring the name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name
