- name: configuring the nodejs
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | bash - 

- name: Installing Nodejs
  ansible.builtin.package:
    name: nodejs 
    state: present

- name: Creating App User
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: download and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract

- name: Generating the artifacts with npm install
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}

- name: Configuring {{COMPONENT}} the service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: configuring the name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name
