- name: configuring the nodejs
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | bash - 

- name: Installing Nodejs
  ansible.builtin.package:
    name: nodejs 
    state: present

- name: Creating App User
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: download and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download and extract

- name: Generating the artifacts with npm install
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}

- name: Copying the systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Starting {{COMPONENT}} 
  systemd:
    name: "{{COMPONENT}}"
    state: started
    enabled: yes
    daemon_reload: yes     

- name: configuring the service name
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}